### ISSUE TITLE
WebFlux security configuration not working

### ISSUE THREAD

**Issue by Zaparix** [spring-projects/spring-security-reactive#11]
Hi,
I have a [dummy project for webflux](https://git.zaparix.de/prototypes/spring-webflux-security-dummy) based on Spring Boot 2.0.0.M5 that provides a REST interface to load and save dummy objects. This project work's fine. Now I wanted to add a security mechanism to the project.

Each controller configures it's own routes, so each controller should configure the security as well. I added a security configuration in the dummy controller and in another controller, but the dummy security always overrides the other configuration... So, I tried to add a security matcher:

```java
  @Bean
  protected RouterFunction< ? > dummyRouterFunctions() {
    return route( POST( BASE_PATH ), this::save )
        .andRoute( GET( BASE_PATH ), this::findAll )
        .andRoute( GET( BASE_PATH + "/{id}" ), this::findById )
        .andRoute( DELETE( BASE_PATH + "/{id}" ), this::deleteProductById );
  }

  @Bean
  protected SecurityWebFilterChain dummySecurityFilter( HttpSecurity http ) {
    return http
        .securityMatcher( new PathPatternParserServerWebExchangeMatcher( BASE_PATH ) )
        .authorizeExchange()
          .pathMatchers( HttpMethod.POST, BASE_PATH )
          .hasRole( "ADMIN" )
        .and().authorizeExchange()
          .pathMatchers( HttpMethod.GET, BASE_PATH )
          .hasRole( "USER" )
        .and().authorizeExchange()
          .pathMatchers( HttpMethod.GET, BASE_PATH + "/{id}" )
          .hasRole( "USER" )
        .and().authorizeExchange()
          .pathMatchers( HttpMethod.DELETE, BASE_PATH + "/{id}" )
          .hasRole( "ADMIN" )
        .and()
        .build();
  }
```
_complete file: [here](https://git.zaparix.de/prototypes/spring-webflux-security-dummy/blob/master/src/main/java/de/zaparix/test/dummy/ui/DummyController.java)_

The result is that routes with the path variable "id" won't work anymore and requests to routes that not exists gets a 200 OK instead of a 404 not found.

I don't know what's wrong. Can anyone help me, please? 😄 

Cheers,
Luca

**Comment by rwinch** [comment]
You have a bug that discovered this bug https://github.com/spring-projects/spring-security/issues/4668

This line of code means that Spring Security will only match the path of  `BASE_PATH` rather than any request that starts with `BASE_PATH`. 

```java
.securityMatcher( new PathPatternParserServerWebExchangeMatcher( BASE_PATH ) )
```
You can remove it or change it to

```java
.securityMatcher( new PathPatternParserServerWebExchangeMatcher( BASE_PATH + "/**") )
```

Some polish

You don't need to do the `.and()` for every rule you set either. So you can simplify to something like:

```java
@Bean
protected SecurityWebFilterChain dummySecurityFilter( HttpSecurity http ) {
  return http
      .authorizeExchange()
        .pathMatchers( HttpMethod.POST, BASE_PATH ).hasRole( "ADMIN" )
        .pathMatchers( HttpMethod.GET, BASE_PATH ).hasRole( "USER" )
        .pathMatchers( HttpMethod.GET, BASE_PATH + "/{id}" ).hasRole( "USER" )
        .pathMatchers( HttpMethod.DELETE, BASE_PATH + "/{id}" ).hasRole( "ADMIN" )
        .and()
      .build();

}
```

PS Please create issues in https://github.com/spring-projects/spring-security/issues going forward as this was an experimental repository. Sorry it was my fault for not marking this as such better.
